# Project information
site_name: 'Bacterial Genome Analysis Workshop, using Galaxy'
site_author: 'Mathis Arnal'
site_url: 'https://mathis-arnal.github.io/Bacterial_Genome_Analysis/'
site_description: Workshop on Metagenomic
# Repository
repo_name: 'mathis-arnal/Bacterial_Genome_Analysis'
repo_url: 'https://github.com/mathis-arnal/Bacterial_Genome_Analysis.git'
edit_uri: edit/main/docs/ # Allow to replace edit/master/docs use by default

# Configuration
theme:
  name: material
  logo: pages/images/IRD.png # logo top left page
  search_index_only: true
  include_search_page: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # collapse subsections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # remove table of content on the right side
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - tables
  - toc:
      permalink: '#'


# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true
  - macros

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

  

# Customization
extra:
  homepage: index.md # Page displayed when clicking the logo
  history_buttons: false
  institute: SouthGreen
  repo: https://github.com/mathis-arnal/Bacterial_Genome_Analysis
  color_table_header: "#333a99"

nav:
  - Home: index.md
  - Schedule: pages/course-information/schedule.md

  - Bacterial Genome Analysis:
      - What is Next Generation Sequencing ?: pages/bacterial/01-intro-ngs.md
      - What is a fastq file ?: pages/bacterial/02-fastq-desc.md
      - Short intro to Galaxy: pages/bacterial/03-short_intro_galaxy.md
      - Assessing Read Quality: pages/bacterial/04-assessing-read-quality.md
      - Trimming and Filtering: pages/bacterial/05-trimming-filtering.md
      - Contamination Checking: pages/bacterial/05-2-contamination.md
      - Assembly: pages/bacterial/06-assembly.md
      - Multi Locus Sequence typing (MLST): pages/bacterial/07-mlst.md
      - Identification of AMR genes: pages/bacterial/08-amr-genes.md
      - Genome Annotation: pages/bacterial/09-genome-annotation.md
